AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  GraphQL:
    Type: AWS::Serverless::Function
    Properties:
      Handler: dist/server.graphqlHandler
      Runtime: nodejs8.10
      Events:
        AnyRequest:
          Type: Api
          Properties:
            Path: /
            Method: ANY